---
"$schema": http://json-schema.org/draft-04/hyper-schema
id: schemata/app
title: FIXME - App
description: FIXME
stability: prototype
strictProperties: true
type:
- object
definitions:
  id:
    description: unique identifier of app
    readOnly: true
    type:
    - integer
  name:
    description: unique name of app
    readOnly: true
    type:
    - string
    "pattern": "^(\\([0-9]{3}\\))?[0-9]{3}-[0-9]{4}$"
  identity:
    anyOf:
    - "$ref": "/schemata/app#/definitions/id"
    - "$ref": "/schemata/app#/definitions/name"
  description:
    description: discription of app
    type: string
    maxLength: 140
  created_at:
    description: when app was created
    format: date-time
    type:
    - string
  updated_at:
    description: when app was updated
    format: date-time
    type:
    - string
links:
- description: Create a new app.
  href: "/apps"
  method: POST
  rel: create
  schema:
    properties: {}
    type:
    - object
  title: Create
- description: Delete an existing app.
  href: "/apps/{(%2Fschemata%2Fapp%23%2Fdefinitions%2Fid)}"
  method: DELETE
  rel: destroy
  title: Delete
- description: Info for existing app.
  href: "/apps/{(%2Fschemata%2Fapp%23%2Fdefinitions%2Fid)}"
  method: GET
  rel: self
  title: Info
- description: List existing apps.
  href: "/apps"
  method: GET
  rel: instances
  title: List
  targetSchema:
    type: object
    properties:
      list:
        type: array
        items:
          type: object
          $ref: "/schemata/app#"
      meta:
        type: object
        properties:
          page:
            type: integer
- description: Update an existing app.
  href: "/apps/{(%2Fschemata%2Fapp%23%2Fdefinitions%2Fid)}"
  method: PATCH
  rel: update
  schema:
    properties: {}
    type:
    - object
  title: Update
properties:
  created_at:
    "$ref": "/schemata/app#/definitions/created_at"
  description:
    "$ref": "/schemata/app#/definitions/description"
  id:
    "$ref": "/schemata/app#/definitions/id"
  name:
    "$ref": "/schemata/app#/definitions/name"
  created_user:
    "$ref": "/schemata/user#"
  updated_at:
    "$ref": "/schemata/app#/definitions/updated_at"
