/*
 * Kyouen API
 *
 * Kyouen server's API.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Error struct {

	Code int64 `json:"code"`

	Message string `json:"message"`
}
