/*
 * Kyouen API
 *
 * Kyouen server's API.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type LoginParam struct {

	Token string `json:"token"`

	TokenSecret string `json:"token_secret"`
}
