/*
 * Kyouen API
 *
 * Kyouen server's API.
 *
 * API version: 0.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NewStage struct {

	Size int64 `json:"size"`

	Stage string `json:"stage"`

	Creator string `json:"creator"`
}
