name: Deploy Seed to DEV

on:
  workflow_dispatch:

env:
  GCP_PROJECT_ID: api-project-732262258565
  SERVICE_NAME: kyouen-server
  REGION: asia-northeast1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.DEV_WIF_PROVIDER }}
        service_account: ${{ secrets.DEV_WIF_SERVICE_ACCOUNT }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Build and push Docker image for seed
      run: |
        docker build -f Dockerfile.seed -t asia-northeast1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/kyouen-repo/kyouen-seed:${{ github.sha }} .
        docker push asia-northeast1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/kyouen-repo/kyouen-seed:${{ github.sha }}

    - name: Deploy Seed Job to Cloud Run
      run: |
        gcloud run jobs replace <(cat <<EOF
        apiVersion: run.googleapis.com/v1
        kind: Job
        metadata:
          name: kyouen-seed
          namespace: '${{ env.GCP_PROJECT_ID }}'
        spec:
          template:
            spec:
              template:
                spec:
                  containers:
                  - image: asia-northeast1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/kyouen-repo/kyouen-seed:${{ github.sha }}
                    env:
                    - name: GOOGLE_CLOUD_PROJECT
                      value: '${{ env.GCP_PROJECT_ID }}'
                    - name: ENVIRONMENT
                      value: 'dev'
                    resources:
                      limits:
                        memory: 512Mi
                        cpu: 1000m
              parallelism: 1
              completions: 1
        EOF
        ) --region=${{ env.REGION }}

    - name: Execute Seed Job
      run: |
        gcloud run jobs execute kyouen-seed \
          --region=asia-northeast1 \
          --project=${{ env.GCP_PROJECT_ID }} \
          --wait