name: Deploy to Production Environment

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "deploy" to confirm production deployment'
        required: true
        type: string

jobs:
  validate-input:
    name: Validate Deployment Confirmation
    runs-on: ubuntu-latest
    steps:
    - name: Validate confirmation
      run: |
        if [[ "${{ github.event.inputs.confirm }}" != "deploy" ]]; then
          echo "❌ Deployment cancelled. You must type 'deploy' to confirm."
          exit 1
        fi
        echo "✅ Deployment confirmed"

  deploy-prod:
    name: Deploy to Production
    needs: validate-input
    uses: ./.github/workflows/deploy-common.yml
    with:
      environment: prod
      project_id: my-android-server
    secrets:
      wif_provider: ${{ secrets.PROD_WIF_PROVIDER }}
      wif_service_account: ${{ secrets.PROD_WIF_SERVICE_ACCOUNT }}